# Generated by Django 5.2.6 on 2025-09-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersystem',
            options={'ordering': ['Username']},
        ),
        migrations.AlterModelTable(
            name='usersystem',
            table='Usersystem',
        ),
    ]
