# Generated by Django 5.2.6 on 2025-09-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0002_alter_usersystem_options_alter_usersystem_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersystem',
            options={},
        ),
        migrations.AlterModelTable(
            name='usersystem',
            table=None,
        ),
    ]
