# Generated by Django 5.2.6 on 2025-09-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0003_alter_usersystem_options_alter_usersystem_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersystem',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usersystem',
            old_name='Username',
            new_name='username',
        ),
    ]
