# Generated by Django 5.2.6 on 2025-09-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0004_rename_password_usersystem_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersystem',
        ),
    ]
