# Generated by Django 5.2.6 on 2025-10-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('teacher', models.CharField(blank=True, max_length=120)),
                ('semester', models.CharField(db_index=True, max_length=20)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses_course',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('code', 'semester'), name='uq_course_code_semester')],
            },
        ),
    ]
