# Generated by Django 5.2.6 on 2025-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='Course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='Description',
            field=models.TextField(default='', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
