# Generated by Django 5.2.6 on 2025-10-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUserScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('name', models.CharField(max_length=120)),
                ('level', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_user_scale',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('username', 'name'), name='uq_aiuserscale_username_name')],
            },
        ),
    ]
