# Generated by Django 5.2.6 on 2025-10-17 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIUseScale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleLevel',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('ai_usage', models.TextField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('acknowledgement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scale_level',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ScaleRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_type', models.CharField(choices=[('system', 'System'), ('sc', 'SC')], max_length=10)),
                ('owner_id', models.CharField(blank=True, max_length=128, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scale_record',
            },
        ),
        migrations.CreateModel(
            name='ScaleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scale_version',
                'ordering': ['-version'],
            },
        ),
        migrations.DeleteModel(
            name='AIUserScale',
        ),
        migrations.AddIndex(
            model_name='scalerecord',
            index=models.Index(fields=['owner_type', 'owner_id'], name='scale_recor_owner_t_5bfc20_idx'),
        ),
        migrations.AddIndex(
            model_name='scalerecord',
            index=models.Index(fields=['is_public'], name='scale_recor_is_publ_af0076_idx'),
        ),
        migrations.AddField(
            model_name='scaleversion',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='AIUseScale.scalerecord'),
        ),
        migrations.AddField(
            model_name='scalelevel',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='AIUseScale.scaleversion'),
        ),
        migrations.AlterUniqueTogether(
            name='scaleversion',
            unique_together={('record', 'version')},
        ),
    ]
