# Generated by Django 5.2.6 on 2025-10-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIUseScale', '0002_scalelevel_scalerecord_scaleversion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scalerecord',
            options={'ordering': ['-updated_at']},
        ),
        migrations.CreateModel(
            name='AIUserScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_user_scale',
                'ordering': ['-updated_at'],
                'unique_together': {('username', 'name')},
            },
        ),
    ]
